def main():
    print("=========================================================")
    print("\n")
    print("               Welcome to Particle Life")
    print("\n")
    print("  This is a particle-based game of life simulation based")
    print("on random attraction and repulsion between all particle")
    print("classes.")
    print("\n")
    print("=========================================================")
    print("\n")
    print("Controls:")
    print("         'B' - Randomize (Balanced)")
    print("         'C' - Randomize (Chaos)")
    print("         'D' - Randomize (Diversity)")
    print("         'F' - Randomize (Frictionless)")
    print("         'G' - Randomize (Gliders)")
    print("         'H' - Randomize (Homogeneity)")
    print("         'M' - Randomize (Medium Clusters)")
    print("         'Q' - Randomize (Quiescence)")
    print("         'S' - Randomize (Small Clusters)")
    print("         'W' - Toggle Wrap-Around")
    print("       Enter - Keep rules, but re-seed particles")
    print("       Space - Hold for slow-motion")
    print("         Tab - Print current parameters to console")
    print("  Left Click - Click a particle to follow it")
    print(" Right Click - Click anywhere to unfollow particle")
    print("Scroll Wheel - Zoom in/out")
    print("\n")
    input()


